export enum EnvKeys {
  REDIS_URL = 'REDIS_URL',
  PUSHER_APP_ID = 'PUSHER_APP_ID',
  PUSHER_KEY = 'PUSHER_KEY',
  PUSHER_SECRET = 'PUSHER_SECRET',
  VERCEL_URL = 'VERCEL_URL',
  FACEBOOK_CLIENT_ID = 'FACEBOOK_CLIENT_ID',
  FACEBOOK_CLIENT_SECRET = 'FACEBOOK_CLIENT_SECRET',
  NEXTAUTH_SECRET='NEXTAUTH_SECRET'
}
